In [ ]:
from google.colab import files
uploaded = files.upload()

Saving vehicle_1.csv to vehicle_1.csv
Saving vehicle_2.csv to vehicle_2.csv
Saving vehicle_3.csv to vehicle_3.csv
Saving vehicle_4.csv to vehicle_4.csv
Saving vehicle_5.csv to vehicle_5.csv
Saving vehicle_6.csv to vehicle_6.csv
Saving vehicle_7.csv to vehicle_7.csv
Saving vehicle_8.csv to vehicle_8.csv
Saving vehicle_9.csv to vehicle_9.csv
Saving vehicle_10.csv to vehicle_10.csv


In [ ]:
import pandas as pd
import io

df1 = pd.read_csv(io.BytesIO(uploaded['vehicle_1.csv']))
df2 = pd.read_csv(io.BytesIO(uploaded['vehicle_2.csv']))
df3 = pd.read_csv(io.BytesIO(uploaded['vehicle_3.csv']))
df4 = pd.read_csv(io.BytesIO(uploaded['vehicle_4.csv']))
df5 = pd.read_csv(io.BytesIO(uploaded['vehicle_5.csv']))
df6 = pd.read_csv(io.BytesIO(uploaded['vehicle_6.csv']))
df7 = pd.read_csv(io.BytesIO(uploaded['vehicle_7.csv']))
df8 = pd.read_csv(io.BytesIO(uploaded['vehicle_8.csv']))
df9 = pd.read_csv(io.BytesIO(uploaded['vehicle_9.csv']))
df10 = pd.read_csv(io.BytesIO(uploaded['vehicle_10.csv']))


       timestamp  longitude   latitude  mileage     speed  fuelLevel  \
0     1637190160   12.48759  55.607189      NaN  9.854212        NaN   
1     1637190160   12.48759  55.607189      NaN  9.854212        NaN   
2     1637190160   12.48759  55.607189      NaN  9.854212        NaN   
3     1637190160   12.48759  55.607189      NaN  9.854212        NaN   
4     1637190160   12.48759  55.607189      NaN  9.854212        NaN   
...          ...        ...        ...      ...       ...        ...   
1494  1637190160   12.48759  55.607189      NaN  9.854212        NaN   
1495  1637190160   12.48759  55.607189      NaN  9.854212        NaN   
1496  1637190160   12.48759  55.607189      NaN  9.854212        NaN   
1497  1637190160   12.48759  55.607189      NaN  9.854212        NaN   
1498  1637190160   12.48759  55.607189      NaN  9.854212        NaN   

      isMoving  elevation  road_type  surface_type  temp  open_weatherapi_id  \
0        False         -1        NaN           NaN -0.2

In [ ]:
df1.columns
print(df1.timestamp[0])

1637190160


In [ ]:
from datetime import datetime

timestamp = df1.timestamp[0]
dt_object = datetime.fromtimestamp(timestamp)

print("dt_object =", dt_object)
print("type(dt_object) =", type(dt_object))
# separate
print(dt_object.date())
print(dt_object.time())
#for d in df['datetime']:
#   df['date'] = d.date()
#   df['time'] = d.time()

dt_object = 2021-11-17 23:02:40
type(dt_object) = <class 'datetime.datetime'>
2021-11-17
23:02:40


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#data visualisation
import seaborn as sns     
sns.set()
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
numbers = [1,2,3,4,5,6,7,8,9,10]
value = 1
while value in numbers:
    if value == 5:
        break
    print( 'I\'m # ' + str(value))
    value = value + 1
  
print('Sorry, I had to quit the loop when the value became 5')

I'm # 1
I'm # 2
I'm # 3
I'm # 4
Sorry, I had to quit the loop when the value became 5


In [ ]:
numbers = [1,2,3,4,5,6,7,8,9,10]
value = 1
while value in numbers:
    if value < 5:
        print ('I\'m # ' + str(value))
        value = value + 1
        continue
        print ('I\'m in the if-condition, why are you ignoring me?!')
    elif value == 5:
        break
 
print ('I have reached the last statement in the program and need to exit')

I'm # 1
I'm # 2
I'm # 3
I'm # 4
I have reached the last statement in the program and need to exit


In [ ]:
import numpy as np
#inputs
inputArray = np.array([[35,53,63],[72,12,22],[43,84,56]])
new_col = np.array([[20,30,40]])
# delete 2nd column
arr = np.delete(inputArray , 1, axis = 1)
#insert new_col to array
arr = np.insert(arr , 1, new_col, axis = 1)
print (arr)

[[35 20 63]
 [72 30 22]
 [43 40 56]]


In [ ]:
list =['billy',1]
student = {'ID':{'name':'Abder-Rahman', 'number':'1234'}}
student['ID']

{'name': 'Abder-Rahman', 'number': '1234'}

In [23]:
#Write a Python function that takes a positive integer and returns the sum of the cube of all the positive integers smaller than the specified number
#sum = 0
def sol(n):
  sum=0
  for i in range(n-1,1,-1):
    #print(i**3)
    sum=sum+i**3
  return sum
x = int(input())
print(sol(x))

9
1295


In [26]:
#Write a Python function to find the maximum and minimum numbers from a sequence of numbers.
def max(l):
  l.sort()
  w = len(l)
  max = l[w-1]
  return max
l= [1,3,2,4,5,23,5,65]
print(max(l))

65


In [ ]:
#tuple pr set
if type(x) is a tuple:
  print('Tuple')
elif

In [ ]:
#Write a Python program to check if every consecutive sequence of zeroes 
#is followed by a consecutive sequence of ones of same length in a given string. Return True/False.
def test(str1):
    while '01' in str1:
        str1 = str1.replace('01', '')
    return len(str1) == 0

